name: Call2 GitHub Clone Count Update Everyday
on:
  workflow_call:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "* * * * *"

jobs:
  call-build:
    uses: codump/conlog/.github/workflows/clone.yml@github-config
